# Generated by Django 5.2.6 on 2025-11-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('telegram_message_id', models.CharField(blank=True, max_length=100)),
                ('replied', models.BooleanField(default=False)),
            ],
        ),
    ]
