# Generated by Django 5.2.6 on 2025-11-10 18:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telegramchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchatmessage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
