# Generated by Django 5.2.6 on 2025-11-10 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telegramchatmessage_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchatmessage',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegramchatmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'User Message'), ('admin', 'Admin Reply')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='telegramchatmessage',
            name='original_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_replies', to='core.telegramchatmessage'),
        ),
    ]
