# Generated by Django 5.2.7 on 2025-11-11 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_telegramchatmessage_admin_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=50)),
                ('largo', models.IntegerField()),
                ('medidas', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Cotización'), ('quoted', 'Presupuestado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_budget', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_request', to='core.budget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
