# Generated by Django 5.2.7 on 2025-11-11 10:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_personalizedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='imagen_referencia',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_referencia'),
        ),
    ]
