# Generated by Django 5.2.7 on 2025-11-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('forma', models.CharField(choices=[('cuadrada', 'Cuadrada'), ('almendra', 'Almendra'), ('redonda', 'Redonda'), ('stiletto', 'Stiletto'), ('coffin', 'Coffin'), ('ballerina', 'Ballerina')], default='almendra', max_length=20)),
                ('tamaño', models.CharField(choices=[('xs', 'Tamaño 1, xs'), ('s', 'Tamaño 2, s'), ('m', 'Tamaño 3, m'), ('l', 'Tamaño 4, l')], default='s', max_length=10)),
                ('color_principal', models.CharField(choices=[('rosa', 'Rosa'), ('rojo', 'Rojo'), ('amarillo', 'Amarillo'), ('negro', 'Negro'), ('plateado', 'Plateado'), ('blanco', 'Blanco'), ('azul', 'Azul'), ('celeste', 'Celeste'), ('naranja', 'Naranja'), ('violeta', 'Violeta'), ('dorado', 'Dorado'), ('verde', 'Verde'), ('transparente', 'Transparente')], max_length=20)),
                ('color_secundario', models.CharField(blank=True, choices=[('rosa', 'Rosa'), ('rojo', 'Rojo'), ('amarillo', 'Amarillo'), ('negro', 'Negro'), ('plateado', 'Plateado'), ('blanco', 'Blanco'), ('azul', 'Azul'), ('celeste', 'Celeste'), ('naranja', 'Naranja'), ('violeta', 'Violeta'), ('dorado', 'Dorado'), ('verde', 'Verde'), ('transparente', 'Transparente')], max_length=20, null=True)),
            ],
        ),
    ]
